CREATE DATABASE cps;
USE cps;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL ,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(250) NOT NULL
);

SELECT * FROM usuarios